root_path = '/home/zsun/work/summer/BagofFrames4AcousticSceneClassification'
file_path = '/home/zsun/work/summer/file'
model_path = '/home/zsun/work/summer/model'
label_path = '/home/zsun/work/summer/label'
data_path = '/home/zsun/work/summer/data/audio_naive'
vocabulary_path = '/home/zsun/work/summer/data'
